name: Wheel building

on:
  push:
    branches:
      - main

jobs:
  build_wheel:
    name: Build wheel on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-22.04
          - ubuntu-latest
          - macos-latest
          - macos-13 # macos-13 is x86_64, macos-latest is arm64
          - windows-latest
    env:
      MUJOCO_PATH: ${{ github.workspace }}
      MUJOCO_PLUGIN_PATH: ${{ github.workspace }}/plugin
      UV_PYTHON: "3.14"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install build dependencies
        run: bash ./.github/workflows/helper.sh install_deps

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "latest"

      - name: Prepare MuJoCo build
        run: bash ./.github/workflows/helper.sh prepare_build

      - name: Compile MuJoCo
        run: bash ./.github/workflows/helper.sh build_mujoco

      - name: Build mujoco python wheel
        run: bash ./.github/workflows/helper.sh build_wheel_and_sdist

      - name: Upload Python wheels and sdists
        uses: actions/upload-artifact@v4
        with:
          name: python-wheels-${{ matrix.os }}
          path: python/dist/*
          retention-days: 14
